---
name: POE-Component-SmokeBox-Uploads-Rsync
version: 0.01
author:
  - 'Apocalypse <APOCAL@cpan.org>'
abstract: Obtain uploaded CPAN modules via rsync
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=POE-Component-SmokeBox-Uploads-Rsync
  homepage: http://search.cpan.org/dist/POE-Component-SmokeBox-Uploads-Rsync
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-poe-smokebox-uploads-rsync
requires:
  File::Rsync: 0
  File::Spec: 0
  POE: 0
  POE::Component::Generic: 0
  POE::Session::AttributeBased: 0
  perl: 5.008
configure_requires:
  Module::Build: 0.35
dynamic_config: 0
provides:
  POE::Component::SmokeBox::Uploads::Rsync:
    file: lib/POE/Component/SmokeBox/Uploads/Rsync.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
